"""Case table row B5 (design.md): a background-job waiting frame is up
(``job_background_open()`` True, ``sess.status == Status.IDLE``) and a
new message is delivered straight to the running agent
(``delivered_to_agent``). The waiting card must re-anchor even though
nothing new is being generated by the parent turn — R4's whole reason
for running the sync/consume check EVERY tick, ``waiting`` or not.

Driven through ``_animate_tick`` directly (not itself one of
entrypoints.md's exported surfaces) because there is no OTHER way to
simulate "one tick of the spinner loop, while waiting" without spinning
up the real background task — the case-table row is about what a tick
DOES, and every assertion below is still made through the same mocked
Telegram boundary entrypoints.md documents.
"""

from __future__ import annotations

from unittest.mock import MagicMock

from aipager import preferences as prefs
from aipager.policy_snapshot import delete_notes, list_outstanding_notes
from aipager.state import Status

CHAT_ID = -2002


def _update(mk_update, text, message_id, user_id=12345):
    return mk_update(text, message_id=message_id, user_id=user_id, chat_id=CHAT_ID)


def test_b5_waiting_card_reanchors_to_message_delivered_to_agent(
    wired, mk_update, run_async, rich_calls, append_queue_op,
):
    bot, sess, injected = wired
    prefs.set_preference(sess.scope_chat_id, "layout", "card")

    run_async(bot._handle_message(_update(mk_update, "hello?", message_id=1),
                                  MagicMock()))
    c1 = sess.busy_msg_id

    run_async(bot._handle_message(_update(mk_update, "check on that",
                                          message_id=2), MagicMock()))
    assert sess.trigger_msg_id == 1

    notes = list_outstanding_notes(sess.name)
    m1_note = next(n for n in notes if n.get("msg_id") == 1)
    m2_note = next(n for n in notes if n.get("msg_id") == 2)
    delete_notes(sess.name, [m1_note])

    # The parent turn produced an interim Stop while a background agent
    # it launched is still running — job_background_open() reads this as
    # a waiting frame, not a fresh turn. The MessageDisplay hook was
    # already live earlier in that same turn (a real prerequisite for
    # exact-anchor scanning to run at all) — simulate that directly
    # rather than replaying the whole parent turn's own assistant_text
    # chunks just to reach the same state.
    sess.stream_hook_live = True
    sess.status = Status.IDLE
    sess.active_subagents = {"agent-1": {"type": "general-purpose",
                                         "started_at": 0.0, "tool_count": 0,
                                         "tools": []}}
    assert sess.job_background_open() is True

    append_queue_op(sess, "remove", "delivered_to_agent", m2_note["body"])

    # One tick of the spinner loop while waiting.
    run_async(bot._animate_tick(sess, "Working", True))

    assert sess.trigger_msg_id == 2, "R2: consumption moves the target"
    assert sess.busy_card_trigger == 2, "R3: re-anchors even while waiting"
    assert sess.busy_msg_id and sess.busy_msg_id != c1

    bot._app.bot.delete_message.assert_any_await(
        chat_id=CHAT_ID, message_id=c1,
        # 8.26 R3: the re-anchor's delete of the OLD card is an
        # ORNAMENT — card housekeeping. Leaving a stale card behind
        # is cosmetic; taking an answer's token to remove it is not.
        rate_limit_args={"class": "ornament"},
    )
    reanchor_send = next(
        c for c in bot._app.bot.send_message.await_args_list
        if c.kwargs.get("reply_to_message_id") == 2
    )
    assert reanchor_send.kwargs.get("disable_notification") is True

    # The job actually finishes now — its single final answer follows M2.
    sess.active_subagents = {}
    sess.job_continuation_active = False
    sess.job_grace_until = 0.0
    run_async(bot.notify(sess, "idle_prompt", {
        "summary": "job done", "raw_md": "job done",
    }))
    answer_payload = next(p for m, p in rich_calls if m == "sendRichMessage")
    assert answer_payload["reply_to_message_id"] == 2
